league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH2_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH2_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH2_ENCRYPTION_KEY)%'
    resource_server:
        public_key: '%env(resolve:OAUTH2_PUBLIC_KEY)%'
    scopes:
        available: ['email']
        default: ['email']
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
