services:
    _defaults:
        autowire: true
        autoconfigure: true

    TestingInfrastructure\:
        resource: '../features/bootstrap/TestingInfrastructure/*'

    #Contexts
    TestingInfrastructure\Context\Trail\TrailContext:
        public: true
        arguments:
            - '@kernel'

    TestingInfrastructure\Context\Register\RegisterContext:
        public: true
        arguments:
            - '@kernel'

    TestingInfrastructure\Context\User\UserContext:
        public: true
        arguments:
            - '@kernel'

    TestingInfrastructure\Context\Authentication\AuthenticateContext:
        public: true
        arguments:
            - '@kernel'

    #Repositories
    Infrastructure\Repository\DoctrineTrailRepository:
      alias: TestingInfrastructure\Repositories\BehatDoctrineTrailRepository

    TestingInfrastructure\Repositories\BehatDoctrineTrailRepository:
      public: true
      arguments:
        - '@Doctrine\ORM\EntityManagerInterface'

